In [1]:
import torch
from transformers import *

In [2]:
model_class = BertModel
tokenizer_class = BertTokenizer
pretrained_weights = 'bert-base-uncased'

In [3]:
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)

In [4]:
model = model_class.from_pretrained(pretrained_weights)

In [5]:
text = "Here is some text to encode. I like cats"

In [6]:
tokenizer.tokenize(text)

['here', 'is', 'some', 'text', 'to', 'en', '##code', '.', 'i', 'like', 'cats']

In [8]:
input_ids = torch.tensor([tokenizer.encode(text, add_special_tokens=True)])
# Add special tokens takes care of adding [CLS], [SEP], <s>... tokens in the right way for each model.
input_ids

tensor([[  101,  2182,  2003,  2070,  3793,  2000,  4372, 16044,  1012,  1045,
          2066,  8870,   102]])

In [9]:
input_ids.shape

torch.Size([1, 13])

In [20]:
with torch.no_grad():
    hidden_states = model(input_ids, output_hidden_states=True)  # Models outputs are now tuples

In [21]:
len(hidden_states)

3

In [29]:
hidden_states[0]

tensor([[[-0.1193,  0.1354, -0.1209,  ..., -0.1926,  0.4788,  0.8122],
         [-0.5715, -0.5945,  0.2095,  ..., -0.6224, -0.1390, -0.1068],
         [-0.2825, -1.1164,  0.1891,  ..., -0.3575, -0.1634,  0.9290],
         ...,
         [ 0.3440,  0.8244,  0.8621,  ...,  0.0089,  0.0491,  0.4598],
         [ 0.1528,  0.3790, -0.0956,  ..., -0.3335, -0.0429,  0.7374],
         [ 0.4121,  0.4205,  0.5157,  ...,  0.2418, -0.2858,  0.1793]]])

In [23]:
hidden_states[1].shape

torch.Size([1, 768])

In [31]:
hidden_states[2][-2]

tensor([[[ 0.1709, -0.3621,  0.1107,  ..., -0.1654,  0.2292,  0.3603],
         [-0.5941, -0.8808, -0.0578,  ..., -0.5638, -0.1473,  0.4646],
         [-0.3492, -1.2916,  0.5962,  ..., -0.7865,  0.1800,  1.3766],
         ...,
         [ 1.0754,  1.4931,  0.9984,  ..., -0.6562, -0.4135,  0.5952],
         [ 0.0772,  0.3939, -0.1480,  ..., -0.3835, -0.6173,  0.6801],
         [ 0.1475, -0.1795,  0.1882,  ...,  0.1265, -0.0474, -0.0017]]])

In [17]:
last_hidden_states[0]

NameError: name 'last_hidden_states' is not defined

In [32]:
from transformers import BertForSequenceClassification
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', return_dict=True)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [34]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
text_batch = ["I love Pixar.", "I don't care for Pixar."]
encoding = tokenizer(text_batch, return_tensors='pt', padding=True, truncation=True)
input_ids = encoding['input_ids']
attention_mask = encoding['attention_mask']

In [35]:
encoding

{'input_ids': tensor([[  101,  1045,  2293, 14255, 18684,  2099,  1012,   102,     0,     0,
             0,     0],
        [  101,  1045,  2123,  1005,  1056,  2729,  2005, 14255, 18684,  2099,
          1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
input_ids

In [ ]:
attention_mask

In [ ]:
torch.tensor([1,0]).unsqueeze(0)

In [ ]:
attention_mask

In [ ]:
torch.tensor([1,0]).unsqueeze(0)

In [ ]:
from transformers import AutoModelForTokenClassification, AutoTokenizer
import torch

model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english", return_dict=True)

In [ ]:
attention_mask

In [ ]:
torch.tensor([1,0]).unsqueeze(0)

In [ ]:
from transformers import AutoModelForTokenClassification, AutoTokenizer
import torch

model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english", return_dict=True, from_tf=True)

In [ ]:
model

tensor([[  101,  1045,  2293, 14255, 18684,  2099,  1012,   102,     0,     0,
             0,     0],
        [  101,  1045,  2123,  1005,  1056,  2729,  2005, 14255, 18684,  2099,
          1012,   102]])

In [37]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [38]:
torch.tensor([1,0]).unsqueeze(0)

tensor([[1, 0]])

In [5]:
from transformers import AutoModelForTokenClassification, AutoTokenizer
import torch

model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english", return_dict=True, from_tf=True)

All TF 2.0 model weights were used when initializing BertForTokenClassification.

Some weights of BertForTokenClassification were not initialized from the TF 2.0 model and are newly initialized: ['bert.embeddings.position_ids']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
